name: Smart Contracts Tests

on:
  push:
    branches:
      - "*"

jobs:
  test:
    name: Run Smart Contract Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: 'lts'  # Use the latest LTS (Long Term Support) version of Node.js

      - name: Install dependencies
        run: npm ci

      - name: Run npm test script
        run: npm test
