name: Smart Contracts Tests

on:
  push:
    branches:
      - "*"  # Trigger on push to any branch

jobs:
  test:
    name: Run Smart Contract Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci  # Use npm ci for faster, reproducible builds

      - name: Run npm test script
        run: npm test
